### ISSUE TITLE
pyradio

### ISSUE THREAD

**Issue by attuska** [uhulinux/ub-ubk5#1]
attila@derp-x8664:/usr/src/UHUBUILD/UB-UBK4$ pyradio
>Error: Module "dateutil" not found!
>
>Please install the above module and try again.

>Debian based distros:
>sudo apt install python3-dateutil
>
>Arch based distros:
>sudo pacman install python-dateutil

>Fedora based distros:
>sudo dnf install python-dateutil

>openSUSE based distros:
>sudo zypper install python3-dateutil
>
>If everything else fails, try:
python -m pip install dateutil
or
python3 -m pip install dateutil
or even
python -m pip install --user dateutil

attila@derp-x8664:/usr/src/UHUBUILD/UB-UBK4$ 

UBK5 detto

**Comment by attuska** [comment]
UBK4-en megoldva. https://github.com/uhulinux/ub-ubk4/commit/94cd2cbc4c464ae4e17274e54b8ac2bc8ae0cf60

**Comment by rezso** [comment]
https://github.com/uhulinux/ub-ubk5/commit/815eb3824bfb521d28bab8f84ddf6f9d259ae8a4
