### ISSUE TITLE
pysolfc sound

### ISSUE THREAD

**Issue by attuska** [uhulinux/ub-ubk5#3]

**Comment by attuska** [comment]
A pysolfc hangjához kellene a pygame, azzal UBK4-en végre van hangja.
Én nem tudom lefordítani az sdl2-t, sem a pygame-t, mert mindegyik az sdl2 illegális utasításánál megfeneklik.
A másik lehetséges megoldás a pysolfc kihajítása a kukába. Ez a könnyebb.

**Comment by rezso** [comment]
UBK5-ön eleve nincs pysolfc, csak pysol-cards, ami a freecell-solver függősége.
