### ISSUE TITLE
gnome software

### ISSUE THREAD

**Issue by attuska** [uhulinux/ub-ubk5#4]

**Comment by attuska** [comment]
Kilép ilyen üzenettel:
>attila@derp-x8664:~$ gnome-software
/usr/lib/gtk-4.0/4.0.0/printbackends/libprintbackend-file.so: undefined symbol: gtk_printer_option_set
Failed to load module: /usr/lib/gtk-4.0/4.0.0/printbackends/libprintbackend-file.so
/usr/lib/gtk-4.0/4.0.0/printbackends/libprintbackend-cups.so: undefined symbol: gtk_printer_option_set
Failed to load module: /usr/lib/gtk-4.0/4.0.0/printbackends/libprintbackend-cups.so
10:54:54:018 Gtk Unknown key gtk-modules in /home/attila/.config/gtk-4.0/settings.ini
Érvénytelen utasítás (core készült)
attila@derp-x8664:~$

**Comment by rezso** [comment]
Nálam nem lép ki, de ezzel együtt használhatatlan. Felhoz 2 nem létező "frissítést", után meg folyamatosan nyűglődik a terminálban:
20:29:23:131 Gs  Only 5 apps for curated list, hiding
20:31:59:168 Gs  No AppStream data, try 'make install-sample-data' in data/
20:32:25:939     Error checking authorization for action id org.freedesktop.packagekit.trigger-offline-update: GDBus.Error:org.freedesktop.PolicyKit1.Error.Failed: Action org.freedesktop.packagekit.trigger-offline-update is not registered
20:32:25:943     Error checking authorization for action id org.freedesktop.packagekit.trigger-offline-update: GDBus.Error:org.freedesktop.PolicyKit1.Error.Failed: Action org.freedesktop.packagekit.trigger-offline-update is not registered

Nagyon gondolkozom rajta, hogy kell-e egy ilyen szutyok.

Az undefined symbol: gtk_printer_option_set pedig egyszerűen egy gtk4 bug: https://gitlab.gnome.org/GNOME/gtk/-/issues/6003

**Comment by rezso** [comment]
Akkor viszont nálunk van elcseszve valami.
Most ezeket hozta fel frissíthetőként.
A három közül csak a chromium az, ami ténylegesen frissíthető, a joe és a libidn nem. Még forráskód szinten sincs belőlük újabb, nemhogy uhu csomagként.

![Képernyőkép 2023-09-20 23-14-12](https://github.com/uhulinux/ub-ubk5/assets/2437550/ea04d96e-d1c5-47e3-ab5a-3f4ee73dc000)

**Comment by rezso** [comment]
Ki fogom dobni ezt a vackot.
Most csak egy csomagot hozott frissíthetőként, a joe-t (ami megint nem lett frissítve ugye), és az állítólagos frissítés után újraindította a gépet úgy, hogy induláskor udev hibát okozott. Másodjára indult el csak a rendszer normálisan.
Fals frissítési jelzés, felesleges, és hibát okozó rendszer újraindítás - konkrétan veszélyes a cucc.

**Comment by attuska** [comment]
Veszélyes a kidobása, hisz ez a "vacak" mégiscsak a gnome alapvető része!
A kidobása azt hozná magával, hogy elsőként magába a gnome dash -ba is bele kellene nyúlni.
Szerintem nem kell sietni vele, hisz nálunk okosabbak (A gnome-software fejlesztői is ügyködne rajta remélhetőleg.

**Comment by attuska** [comment]
Felfrissítettem a pendrájvon lévő  egész rendszert, most ezt mondja terminálban:

attila@derp-x8664:~$ gnome-software
11:41:29:054 Gtk Unknown key gtk-modules in /home/attila/.config/gtk-4.0/settings.ini
Érvénytelen utasítás (core készült)
attila@derp-x8664:~$ 

Az érvénytelen utasítás a CPU nem tudja értelmezni. (Fordító hiba??)

**Comment by rezso** [comment]
A következő nagy frissítés (amin most dolgozom) után nem lesz ilyen gond, mert kidobtam. (Ahogy a kde-s apper és discover csomagokat is.)
Úgy tűnik, a packagekit nem kompatibilis az UHU-val, pl. mert nem ismeri az .uhu fájlokat. Így viszont nincs értelme.

**Comment by attuska** [comment]
Most a discover még jól működik!

**Comment by rezso** [comment]
De kell nekünk egy "kde-s synaptic"? Szerintem nem. A dpkg - apt - synaptic trió régóta stabilan működik, nem hiszem, hogy valóban szükség lenne a discover-re.

**Comment by attuska** [comment]
Lehet, hogy a Black-Panther jár jó úton, hogy az egész gtk bandát kidobta és csak QT meg plasma van náluk?

**Comment by rezso** [comment]
Azt semmiképp nem gondolnám. És mostanra azért a gtk is szelídült: anno, amikor Karesz nekiállt, folyamatos API váltások voltak a gtk-ban (ahogy az ffmpeg-ben is), ezt gyűlölte, jogosan.
A gnome viszont tényleg kritikán aluli, ami a felépítését, összerakását illeti.

**Comment by attuska** [comment]
Szerintem azért okosabbak és tapasztaltabbak a gnome, meg gtk karbantartók, mint Karesz. Ez nem Karesz lebecsülése! Tény, hogy a gnome, meg gtk is továbbra is alapja szinte az összes létező desktopnak. Talán még ez a nyomorult gnome-software is rendbetehető nálunk. Az más kérdés, hogy az "uhusítása" biztosan nem lesz egyszerű.
