### ISSUE TITLE
sddm-config-editor segfault

### ISSUE THREAD

**Issue by attuska** [uhulinux/ub-ubk5#5]

**Comment by attuska** [comment]
Menüpontja nincs.
A --help parmétert megadva neki elindul, de továbbra is seggreül, a breeze téma használhatatlan.

**Comment by attuska** [comment]
Szerintem valamennyi nagyobb desktop környezetet ki kellne dobni, csak egyet meghagyni alapértelmezettnek, mert csak hibák garmadaját okozzák az egyebek.
Nagy kérdés, hogy melyik legyen a megmaradó? A Plasma kidobása után megmaradna a gnome, melyben a softwere nem működik. A Cinnamon már hála Neked ki lett dobva. A Mate maradjon, vagy az xfce4? Egyik sem wayland képes még!

**Comment by rezso** [comment]
Ha én kidobok desktopot, az a gnome és az lxde lesz. Az lxde évek óta nem karbantartott, és a menu-cache és az lxmenu-data kivételével semmi nem kell belőle másnak.
A gnome pedig baromi rapszodikus, össze-vissza vannak a verziószámok, a függőségekről nem is beszélve. (Mivel szereted a játékokat, erre egy példa: a gnome-nibbles már frissíthető lenne a 4.0.1-re, de annak már a gtk4-es libgnome-games-support kellene, míg az összes többi játék még gtk3-as. Így egyazon lib két verziója kellene.)
Arról pedig még nem is beszéltem, hogy a gnome fejlesztők imádják a vala-t, ami megint sok problémát okozott már eddig is.
Ja és persze ott van az is, hogy a gnome-software használhatatlan, míg a kde-s discover jól működik szerinted (én nem próbáltam.) Akkor most miért is a plasma legyen kidobva? Az legalább konzisztens.
A wayland pedig engem speciel nem hoz lázba.

**Comment by rezso** [comment]
De hogy az sddm-ről is legyen szó: jó eséllyel a kde része lesz (https://invent.kde.org/plasma/plasma-desktop/-/issues/91), az azon belüli beállítást meg eddig is az sddm-kcm végezte.
Az sddm-config-editor eredetileg lxqt projekt volt (https://github.com/lxqt/sddm-config-editor), de azt leváltotta az sddm-conf (https://github.com/qtilities/sddm-conf).
Meglátjuk, mi lesz belőle. A breeze téma pedig a plasma-workspace része (legalábbis az sddm-nél), kéretik a kde fejlesztőknek reklamálni miatta.

**Comment by attuska** [comment]
Letöltöttem a számomra új forrásból az sddm-conf -ot, lefordítottam, de nincs semmi változás, továbbra is seggreül nálunk rapszódikusan, egyelőre marad a régi.
A maya téma továbbra is jó, de a plasma-ban alapértelmezett plasma téma a preview -ben továbbra is qml hibát dob, továbbra is használhatatlan. Marad a vésztéma.
A  hibák, amiket olvasni tudok:
>org.kde.plasma.extras is not installed
org.kde.plasma.components is not installed
org.kde.plasma.core is not installed
QtGraphicalEffects is not installed

Ezek a téma Main.qml fájljában vannak:
>import QtQuick 2.15
import QtQuick.Layouts 1.15
import QtQuick.Controls 2.15 as QQC2
import QtGraphicalEffects 1.15
>
>import org.kde.plasma.core 2.0 as PlasmaCore
import org.kde.plasma.components 3.0 as PlasmaComponents3
import org.kde.plasma.extras 2.0 as PlasmaExtras
>
>import "components"
import "components/animation"

Ezek szerint nálunk a qtquick és a plasma nem működik rendesen, ha másutt (például Arch -linux) nyilván megy.

**Comment by rezso** [comment]
A plasma-framework kell neki.

**Comment by attuska** [comment]
Telepítve van.

**Comment by rezso** [comment]
UBK5 alatt nekem jól működik. Terminálból indítva csak ennyit ír:
Empty filename passed to function
qt.svg: <input>:1646:6: Could not resolve property: #linearGradient4636
qt.svg: <input>:1646:6: Could not resolve property: #linearGradient4592
qt.svg: <input>:1646:6: Could not resolve property: #linearGradient4247
De ez sem zavar be semmibe.

**Comment by attuska** [comment]
Nálam a tökre frissített UBK5 pendrive telepítményemen:
1. Egyáltalán nincs menüpontja, csak terminálból indítható a begépelt sddm-config-editor paranccsal.
2. A rapszódikusan előjövő grafikus ablakban, mely végre a szegmentációs hibák után csak a maya működik.
3. A még esetleg választható breeze téma hibái a már felsorolt Qtquick gondok. A plasma-framework is telepítve van!

**Comment by rezso** [comment]
A breeze téma majd most lesz jó, a kde6-tal. Az sddm ugyanis már qt6-os, míg a breeze téma qt5-ös.
A konfig az sddm-nél 3 szintem működik.
Van az alap rendszerszintű, az /usr/lib/sddm/sddm.conf.d alatt. Ezt lehet felülírni az /etc/sddm/sddm.conf.d tartalmával. És végül az /etc/sddm.conf a fallback config, ha semmi más nincs.

**Comment by attuska** [comment]
UBK4-en nincs a /usr/lib alatt sddm.conf.d nevő mappa. Az sddm verzója is kisebb, mint UBK5-ön, de az szintén qt6-al lett fordítva. qt5-el fordítva sem eszi meg UBK4-en (UBK5-ön nem próbáltam) a breeze témát.
A plasma egészét az UBK4-en békén hagytam. MInek bántanám, nem kellenek nekem az újabb gondok.
