### ISSUE TITLE
nvidia installer bug

### ISSUE THREAD

**Issue by attuska** [uhulinux/ub-ubk5#7]

**Comment by attuska** [comment]
Megpróbáltam feltelepíteni az nvidia drivert a honlapról letöltött hivatalos nvidia 64 bites telepítő önkicsomagoló telepetítőjévela pendrivere telepített UBK5 telepítményemre.
Itt a reészletes hiba logja, melyet a /var/lib alá hozott létre nekem tanulmányozásra. Mivel ez angolul van, számomra csak nehezen értelmezhető.
[nvidia-installer.log](https://github.com/uhulinux/ub-ubk5/files/14534839/nvidia-installer.log)

**Comment by rezso** [comment]
Semmilyen bug nincs benne. Az nvidia driver nem fér össze a nouveau driverrel, ezért áll le.
Mivel ez csak nvidia driver esetén jelent csak gondot, ezért egyénileg kell megoldani a nouveau driver letiltásával.
https://docs.nvidia.com/ai-enterprise/deployment-guide-vmware/0.1.0/nouveau.html

**Comment by attuska** [comment]
Rendben, hogy ezt te jónak találod.
Elolvasva a letiltási módot, csak megerősítette az eddigi gyanúmat, hogy  **minden utólagosan kernel modult szállítő csomag esetében az initramdiszk valamilyen módon újragenerálandó** (https://github.com/uhulinux/ub-ubk4/issues/118#issuecomment-1974695128), hogy a szállított modul az initramdiszkbe is belekerüljön, mert máshonnan a rendszer számára már elérhetetlen.

**Comment by rezso** [comment]
Az initramdiszknek csak a rendszer indulásakor van jelentősége, utána már nincs. Itt a nouveau-t azért kell letiltani, és újrageneráltatni az initramdiszket, mert a nouveau és az nvidia ütközik.
Csomagszinten ezt max. úgy tudod megoldani, hogy az nvidia csomaghoz hozzáadsz egy blacklist-et, ami letiltja a nouveau-t, és postinst-be már betehetsz egy mkinitrd-installedkernel parancsot.
Ez viszont kimondottan nvidia nyűg, nem általános probléma.

**Comment by rezso** [comment]
Pl. a virtualbox is kitűnően működik úgy, hogy nincsenek benne a kernelmoduljai az initramdiszkben.

**Comment by attuska** [comment]
Ezt a csomagszinti belenyúlást, meg kell oldani minden csomagnál, vagy kihajítani őket.
Nem csak UBK5 esetében!

**Comment by attuska** [comment]
A virtualboxnál a /etc/modprobe.d mappa úgy tűnik, hogy működik UBK4 esetében. Az lsmod  felhozza az oda rakott kernel modulokat, melyek be is vannak töltve.
A többi modul szállító csomagnál kell kitalálni valami jót.

**Comment by rezso** [comment]
Többi csomag = nvidia csomagok, mert más nem szállít kernel modulokat.
Az nvidia nyűgben pedig nem igazán tudok segíteni, mert nekem intel chiphez nem töltődik be a nouveau, így semmilyen gondot nem okoz.

**Comment by attuska** [comment]
Egyelőre az eddiginél frisebb nvida-470 -es csomagot gyúrom UBK4 alá a Gentoo ebuildja alapján.
Mindent a /usr/lib alá pakol a kernel modulokkal egyetemben. A /etc/modprobe.d értelmezve van, az X11 driver (nvidia) beállítás is. A csomag által szállított kernel modulokat nem leli meg, ezért be sem tudja tölteni a rendszer. A nouveau modult meglelné, de az feketelistán van, ezért nincs is grafika.

**Comment by attuska** [comment]
UBK5 telepítményemen a legújabb nvidia-470 installer megcsinált mindent hibátlanul, elindul, de a 490-es installere  előtte hibába futott. A telepítmény most csakis ezen a gépen és csak X -en ad grafikát, mivel ebben van csak a 470-el kompatibilis nvidia gpu. A 490-essel is kompatibilis, de most nem azzal megy. A meghajtó eltávolítása most egyelőre lehetetlen, legalábbis nekem visszaállítani a nouveaura a rendszert nem sikerült a driver eltávolításával (a --uninstall opcióval) sem.
Valami miatt a nouveau továbbra is feketelistán van.

**Comment by attuska** [comment]
Rendbetettem az USB UBK5 telepítményem
Sikerült levakarnom az nvidia-470-es telepítést és visszaállítanom a nouveau használatára. Ezzel a wayland felületek is elérhetők. Történet:
A sikertelen 490 telepítő félbeszakadt és otthagyott a /etc/modprobe.d alatt egy konfigot, mellyel letiltatta a nouveaut. Ráadásul ezt a konfigot a /usr/lib/modprobe.d alá is berakta, melyek letörlése és sikeres 470-es telepítő futttatásával a --uninstall opcióval ezt megtette. Az említett konfigok letörlése után már végre hordozhatóvá vált az UBK5 telepítmény a jól működő nouveau meghajtóval.
Nem volt könnyű...

**Comment by attuska** [comment]
UBK5-re a még létező nvidia csomagokat én nem fogom megcsinálni. 
Kipróbálni csak az itt még létező nvidia-470-et tudnám. A mostani csomag most nem jó, de a binárisból felrakott meghajtó bizonyítottan működött. UBK4-en végre minden általam próbálható jó. A legújabb nvidia GPU-ra nincs pénzem, vaktában csináltam meg UBK4-re.
